### ISSUE TITLE
GERBER файл

### ISSUE THREAD

**Issue by vovo2dev** [MultiMote/kugoo-s3-bluepill#1]
Здравствуйте, у вас есть возможность выложить разводку платы в формате гербер? Хочу сделать заказ на JLCPCB

**Comment by MultiMote** [comment]
Здравствуйте. Проект содержит в себе [плату](https://github.com/MultiMote/kugoo-s3-bluepill/blob/master/pcb/kugoo-s3-bluepill.dip) в формате [DipTrace](https://diptrace.com/rus/download/download-diptrace). В программе можно выполнить экспорт в формат Gerber с необходимыми вам настройками.

![export](https://user-images.githubusercontent.com/8068160/127664919-3ac092db-16dd-49c8-bab6-135da6637d97.png)

Экспорт с настройками по-умолчанию: [kugoo-s3-bluepill_gerber.zip](https://github.com/MultiMote/kugoo-s3-bluepill/files/6908031/kugoo-s3-bluepill_gerber.zip)
